### ISSUE TITLE
nxt-python-examples: change standard branch from python2 to master

### ISSUE THREAD

**Issue by feinstaub** [schodet/nxt-python#136]
Currently the repository nxt-python-examples seems to be configured that cloning checks out the python2-Branch. Why not the master branch?

**Comment by GolddolphinSKB-Fexcraftian** [comment]
I believe this is because the last release of nxt-python that was regarded as "stable" was on python2, this could probably be updated, but that's @Eelviny 's decision.

**Comment by dlech** [comment]
What do you think about the idea of moving the examples into this repository? I think it would make them easier to find.

**Comment by GolddolphinSKB-Fexcraftian** [comment]
Again, that's @Eelviny 's decision. It might be a good idea.

**Comment by schodet** [comment]
Examples are included in nxt-python repository, closing.
