### ISSUE TITLE
Not finding brick

### ISSUE THREAD

**Issue by letsgo00** [schodet/nxt-python#154]
I cannot get this to work with any of my lego nxt bricks. Uding nxt-python version 2.2.2 (also tried 2.1.0)
Getting this error: 
```
Host: None Name: NXT2 Strict: True
USB: True BT: True Fantom: False FUSB: False FBT: False
Traceback (most recent call last):
  File "message_test.py", line 9, in <module>
    b = nxt.locator.find_one_brick(name="NXT2", debug=True)
  File "C:\Python27\lib\site-packages\nxt\locator.py", line 137, in find_one_brick
    raise BrickNotFoundError
nxt.locator.BrickNotFoundError
```

**Comment by zephirFR** [comment]
Hey, I think I had a similar problem and I got it to work after searching around, so I compiled some useful info that could help :

- Installation : https://github.com/Eelviny/nxt-python/wiki/Installation

For Bluetooth connection:
- Download https://github.com/ev3dev/pybluez and go to its directory
- `sudo python setup.py`
- If error like that (https://stackoverflow.com/questions/21597536/pybluez-installation-in-linux/21597642#21597642), download this required package : `sudo apt-get install libbluetooth-dev` and try again
- Check this guide to connect to your Mindstorm more rapidly : https://github.com/Eelviny/nxt-python/wiki/FAQ
- Test the connection with this:
```
import nxt.bluesock # Make sure you remember this!
b = nxt.bluesock.BlueSock('00:16:53:0E:7E:DE').connect() #replace the string with the one you got earlier
from nxt.motor import *

b.play_tone_and_wait(440.0, 100) # 440Hz is Concert A and 100ms for duration. Basically, make a beep noise to check connection
```

**Comment by schodet** [comment]
python2 is no longer supported, please try with python3 and master branch.
