### ISSUE TITLE
Motor BlockedException

### ISSUE THREAD

**Issue by ashenoy24** [schodet/nxt-python#162]
Hi, I just got set up and I'm having some issues with the example `spin.py`. Running the code produces the following effect. The left motor (as defined in the code connected to port b) runs endlessly, stopping only after the timeout limit is reached. This produces the `BlockedException` that terminates the code. I'm using pyUSB on a OSX machine.

**Comment by schodet** [comment]
This looks like NXT-Python does not have feedback from the NXT, What version are you using? Which version of python are you using?
