### ISSUE TITLE
Ultrasonic and color sensor do not work properly and it reads too slow.

### ISSUE THREAD

**Issue by mmaxus35** [schodet/nxt-python#166]
Hi!

Ultrasonic and colour sensor do not work properly they read random variables and reading processes are too slow. Buffered values might be prompted to the screen.

Thanks

**Comment by schodet** [comment]
Hi!

Could you give more details?

OS, Python version, NXT-Python version, Connection method: USB? Bluetooth?

Do you have a test program?
