### ISSUE TITLE
No backend available

### ISSUE THREAD

**Issue by hardcodedpassword** [schodet/nxt-python#178]
- OS: Mac OS 11.6.1
- Python version: 3.9
- NXT-Python version: 3.0.0a3
- Connection method: USB

I ran into this "No backend avaiable" error and figured out the solution. I think its worth mentioning here.

On Mac, you need to install `libusb`. Open a terminal and enter: 

`brew install libusb`

**Comment by schodet** [comment]
Thanks, I added it to the installation instructions.
