### ISSUE TITLE
EV3 doesn´t connect to NXT (via USB)

### ISSUE THREAD

**Issue by MatykoBr** [schodet/nxt-python#194]
Hello!

I don´t know if NXT-Python is still active, but I have a problem. Every time I try to run the command `nxt_test` the command doesn´t work well, and the console shows this error:

`robot@python-ev3:~/nxt_python$ nxt_test `
`Find brick...`
`Traceback (most recent call last):`
  `  File "/home/robot/.local/bin/nxt_test", line 21, in <module>`
   `    with nxt.locator.find_with_options(options) as b:`
  `  File "/home/robot/.local/lib/python3.5/site-packages/nxt/locator.py", line 289, in find_with_options`
    `    return find(find_all=find_all, **kwargs)`
  `  File "/home/robot/.local/lib/python3.5/site-packages/nxt/locator.py", line 215, in find`
    `    raise BrickNotFoundError('no brick found')`
`nxt.locator.BrickNotFoundError: no brick found`

**Here Are my specs:**

- OS: Windows 10
- Python version: Python 3.5.3
- NXT-Python version: NXT-Python 3.2.0
- Connection method: USB

I would be happy, if anyone could help me.

Thanks,

MatykoBr

**Comment by schodet** [comment]
It’s active :)

NXT-Python only supports the NXT bricks, not the EV3.

**Comment by schodet** [comment]
Hum wait… you run NXT-Python on the EV3 brick to connect to a NXT brick? So your OS is not Windows then.

Have you read https://ni.srht.site/nxt-python/latest/installation.html ?

Can you try to run lsusb?

Can you try with the debug log (`nxt_test --log-level=debug`)?

**Comment by schodet** [comment]
OK, I think you do not have pyusb installed.
