### ISSUE TITLE
[NOOB QUESTION]: How to get rotation angle of motor?

### ISSUE THREAD

**Issue by Starchaser0** [schodet/nxt-python#198]
#### Noob Question:
 - How do I get just the rotation angle of a given motor?

#### Context:
I am currently working on a diy racing wheel that works by taking the angle of a servo motor and using it as joystick input. 

I happen to have some old NXT and Technic parts laying around, so I decided to use those. After some looking, I finally found this amazing project, and started playing around with it. 

However, I am confused by the documentation, and have not figured out how to isolate the rotation angle of a given motor. Any pointers would be appreciated!

I've tried using get_tacho(), and I couldn't figure out how to use OutputState and TachoInfo.

*NOTE: The documentation isn't bad, I'm just relatively new to this kind of programming, so I'm likely the problem here lol*

#### Le specs:
- OS: Fedora 40 (Kernel 6.8.7)
- Python version: 3.12.2
- NXT-Python version: 3.3.0
- Connection method: USB

**Comment by schodet** [comment]
> I did add `angle = None` after `print(angle)` to prevent high memory usage though.

No reason to do this, python will handle memory for you.
