### ISSUE TITLE
Python 3.x support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [schodet/nxt-python#50]
```
Describe the new feature more precisely.

Being able to run the nxt-python using python 3.x
Are there any plans on adding support for 3.x?


Why do you think it's important?

I've wanted to write a motion control script for a long time using nxt and 
blender. I just read this post 
(http://www.eibriel.com/2012/05/06/camera-motion-control-controlling-steppers-wi
th-blender-tutorial/) and really inspired I thought I'd check out if I would be 
able to control my nxt from within blender. Blender uses python 3.x so...


Any ideas on how to implement it?

Sadly no, but I haven't done to much research either..

Please provide any additional information below.

Thank you very much for your time and effort on this module!
```

Original issue reported on code.google.com by `flehnerh...@gmail.com` on 14 Feb 2013 at 7:58

**Comment by Eelviny** [comment]
The master branch is now completely devoted towards Python 3.x development. No working release as of yet, but I've made steps in the right direction. Currently I'm still in the process of getting to grips with the project's code, so if anyone more knowledgeable on it than me sees something that needs fixing feel free to submit a pull request.

**Comment by dlech** [comment]
I think the conversion to Python 3.x is pretty much complete at this point. Maybe time for a release so it gets wider testing?

**Comment by GolddolphinSKB-Fexcraftian** [comment]
Yeah, I believe most py2 -> 3 type issues have been solved.

**Comment by schodet** [comment]
There are alpha releases for Python 3. I think I will make a release as soon as I have finished to write the tutorial.
