### ISSUE TITLE
NXT-PYTHON in browser

### ISSUE THREAD

**Issue by lkvapil** [schodet/nxt-python#78]
Hi,

my idea is to control Lego NXT by NXT PYTHON over the browser. I want to make it 
easiest, but without lines with commands type to write into the console and start the PYTHON script, next start other script .... I mean all into the Python with buttons.. (I dont know, if somebody all ready done it pls. tell :D) Is here somobedy able to spend free time with my idea ? Thanks

**Comment by nikolajovickg** [comment]
Done that with node.js and python, but with console. You can implement what you need with nxt-python and socket.io (and serve static web page with python).

**Comment by lkvapil** [comment]
Could you leave some url ? :D

**Comment by schodet** [comment]
Out of scope, you can build a project using NXT-Python to do this though, using a backend in python and a web page communicating with the backend.
