### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by jbmorris29** [schodet/nxt-python#99]
I've installed NXT-Python, PyBluez, PyUSB, and Pyfantom, but I keep getting this error when I just try importing nxt.locator:

 ~/Python/nxt-python-2.2.2/scripts $ python nxttry.py 
Traceback (most recent call last):
  File "nxttry.py", line 1, in <module>
    import nxt.locator
ImportError: No module named locator

I get it when I try import nxt.locator, from nxt import locator, and import nxt then import locator.

Any help would be appreciated.

**Comment by GolddolphinSKB-Fexcraftian** [comment]
`import nxt.locator`

**Comment by GolddolphinSKB-Fexcraftian** [comment]
Have you got a folder called ``nxt`` in the directory? It may be trying to find the module in there.

**Comment by feinstaub** [comment]
@jbmorris29: any luck with the hint from GolddolphinSKB-Fexcraftian ?

**Comment by schodet** [comment]
No response, closing.
